<html>
  @extends('layouts.master_bootstrap')
  <head>
　  <title>ユーザー</title>
　</head>
　<body>
　  <h1>ユーザー個人</h1>
　  {{$user->id}}
　  {{$user->name}}
　  {{$user->email}}
　  {{$user->password}}
　</body>
</html>
